<?php
/**
 * V2 public website route metadata registry.
 */

defined( 'GECKO_CLIENT_VERSION' ) OR exit( 'No direct script access allowed' );

$routes_v2 = [];

$routes_v2['public'] = [
    'home' => [
        'path'        => '/',
        'title'       => 'Market Overview',
        'description' => 'Track live cryptocurrency markets, TON ecosystem context, trending assets, exchanges, and shareable market links from TONBANKCARD Crypto Tracker.',
        'og_type'     => 'website',
        'schema_type' => 'CollectionPage',
        'sitemap_changefreq' => 'hourly',
        'sitemap_priority'   => '1.0',
    ],
    'markets' => [
        'path'        => '/markets',
        'title'       => 'Crypto Markets',
        'description' => 'Browse cryptocurrency prices, market capitalization, volume, rank, and recent movement from the TONBANKCARD public market table.',
        'og_type'     => 'website',
        'schema_type' => 'CollectionPage',
        'sitemap_changefreq' => 'hourly',
        'sitemap_priority'   => '0.9',
    ],
    'coins' => [
        'path'                 => '/coins/:id',
        'title_template'       => '%s Price, Chart, and Market Data',
        'description_template' => 'Track %s price, chart history, market capitalization, volume, rank, converter tools, exchange markets, and shareable market context.',
        'og_type'              => 'article',
        'schema_type'          => 'FinancialProduct',
        'sitemap_changefreq'   => 'hourly',
        'sitemap_priority'     => '0.8',
        'sitemap_params'       => [
            [ 'id' => 'bitcoin' ],
            [ 'id' => 'ethereum' ],
            [ 'id' => 'toncoin' ],
        ],
    ],
    'currency' => [
        'path'                 => '/currency/:id',
        'canonical_path'       => '/coins/:id',
        'title_template'       => '%s Price, Chart, and Market Data',
        'description_template' => 'Track %s price, chart history, market capitalization, volume, rank, converter tools, exchange markets, and shareable market context.',
        'og_type'              => 'article',
        'schema_type'          => 'FinancialProduct',
        'sitemap'              => FALSE,
    ],
    'ton' => [
        'path'        => '/ton',
        'title'       => 'TON Ecosystem',
        'description' => 'Explore TON ecosystem market context, Toncoin, TON assets, Telegram-native growth loops, and upcoming TONBANKCARD V2 ecosystem coverage.',
        'og_type'     => 'website',
        'schema_type' => 'CollectionPage',
        'sitemap_changefreq' => 'daily',
        'sitemap_priority'   => '0.8',
    ],
    'wallet-profile' => [
        'path'        => '/wallet',
        'title'       => 'Wallet Profile',
        'description' => 'Connect a TON wallet through TON Connect for optional wallet-aware watchlist and portfolio context without sharing private keys.',
        'og_type'     => 'website',
        'schema_type' => 'ProfilePage',
        'sitemap_changefreq' => 'weekly',
        'sitemap_priority'   => '0.7',
    ],
    'exchanges' => [
        'path'        => '/exchanges',
        'title'       => 'Crypto Exchanges',
        'description' => 'Compare cryptocurrency exchanges by trust score, volume, country, launch year, and market availability through TONBANKCARD Crypto Tracker.',
        'og_type'     => 'website',
        'schema_type' => 'CollectionPage',
        'sitemap_changefreq' => 'daily',
        'sitemap_priority'   => '0.8',
    ],
    'crypto-exchange' => [
        'path'        => '/crypto-exchange',
        'title'       => 'Crypto Exchange',
        'description' => 'Open the TONBANKCARD partner exchange page with TON and supported crypto pairs preselected from search.',
        'og_type'     => 'website',
        'schema_type' => 'WebPage',
        'sitemap_changefreq' => 'weekly',
        'sitemap_priority'   => '0.7',
    ],
    'exchange' => [
        'path'                 => '/exchange/:id',
        'title_template'       => '%s Exchange Markets',
        'description_template' => 'Review %s exchange volume, trust score, normalized liquidity, chart context, and market availability.',
        'og_type'              => 'article',
        'schema_type'          => 'WebPage',
        'sitemap'              => FALSE,
    ],
    'derivatives' => [
        'path'        => '/derivatives',
        'title'       => 'Crypto Derivatives',
        'description' => 'Track cryptocurrency derivatives markets, futures contracts, funding rates, open interest, basis, spreads, and 24-hour volume.',
        'og_type'     => 'website',
        'schema_type' => 'CollectionPage',
        'sitemap_changefreq' => 'daily',
        'sitemap_priority'   => '0.7',
    ],
    'finance-platforms' => [
        'path'        => '/finance-platforms',
        'title'       => 'Crypto Finance Platforms',
        'description' => 'Compare decentralized finance platforms by category, asset coverage, lending markets, and public market context.',
        'og_type'     => 'website',
        'schema_type' => 'CollectionPage',
        'sitemap_changefreq' => 'weekly',
        'sitemap_priority'   => '0.6',
    ],
    'finance-products' => [
        'path'        => '/finance-products',
        'title'       => 'Crypto Finance Products',
        'description' => 'Review public crypto finance products, rates, supported platforms, supply markets, borrow markets, and availability windows.',
        'og_type'     => 'website',
        'schema_type' => 'CollectionPage',
        'sitemap_changefreq' => 'weekly',
        'sitemap_priority'   => '0.6',
    ],
    'screener' => [
        'path'        => '/screener',
        'title'       => 'Crypto Screener',
        'description' => 'Prepare market filters for market cap, movement, volume, category, TON tags, and sentiment as the TONBANKCARD V2 screener evolves.',
        'og_type'     => 'website',
        'schema_type' => 'SearchResultsPage',
        'sitemap_changefreq' => 'daily',
        'sitemap_priority'   => '0.7',
    ],
    'alerts' => [
        'path'        => '/alerts',
        'title'       => 'Smart Alerts',
        'description' => 'Create Telegram bot alerts for price crosses, market movement, volume, rank, sentiment, and TON ecosystem context.',
        'og_type'     => 'website',
        'schema_type' => 'WebApplication',
        'sitemap_changefreq' => 'daily',
        'sitemap_priority'   => '0.7',
    ],
    'achievements' => [
        'path'        => '/achievements',
        'title'       => 'Achievements',
        'description' => 'Opt in to TONBANKCARD achievement badges, streaks, dismissible prompts, and shareable market progress cards.',
        'og_type'     => 'website',
        'schema_type' => 'WebApplication',
        'sitemap_changefreq' => 'weekly',
        'sitemap_priority'   => '0.6',
    ],
    'about' => [
        'path'        => '/about',
        'title'       => 'About TONBANKCARD',
        'description' => 'Learn how TONBANKCARD Crypto Tracker connects public market pages with Telegram-native watchlists, alerts, sharing, and responsible intelligence.',
        'og_type'     => 'website',
        'schema_type' => 'AboutPage',
        'sitemap_changefreq' => 'monthly',
        'sitemap_priority'   => '0.5',
    ],
    'support' => [
        'path'        => '/support',
        'title'       => 'Support',
        'description' => 'Find TONBANKCARD support, official channels, bot help, issue reporting guidance, and safety boundaries for market data and exchange widgets.',
        'og_type'     => 'website',
        'schema_type' => 'ContactPage',
        'sitemap_changefreq' => 'monthly',
        'sitemap_priority'   => '0.5',
    ],
    'terms' => [
        'path'        => '/terms',
        'title'       => 'Terms and Risk Disclosures',
        'description' => 'Read TONBANKCARD terms and risk disclosures for market data, AI summaries, alerts, swap widgets, and third-party providers.',
        'og_type'     => 'website',
        'schema_type' => 'WebPage',
        'sitemap_changefreq' => 'monthly',
        'sitemap_priority'   => '0.4',
    ],
    'privacy-policy' => [
        'path'        => '/privacy-policy',
        'title'       => 'Privacy Policy',
        'description' => 'Review TONBANKCARD privacy coverage for Telegram data, analytics, AI features, alerts, wallet context, and support requests.',
        'og_type'     => 'website',
        'schema_type' => 'WebPage',
        'sitemap_changefreq' => 'monthly',
        'sitemap_priority'   => '0.4',
    ],
    'cookies-policy' => [
        'path'        => '/cookies-policy',
        'title'       => 'Cookies and Local Storage Policy',
        'description' => 'Review how TONBANKCARD uses cookies, local storage, browser storage, and third-party provider storage for the public website and Mini App.',
        'og_type'     => 'website',
        'schema_type' => 'WebPage',
        'sitemap_changefreq' => 'monthly',
        'sitemap_priority'   => '0.4',
    ],
];

$routes_v2['admin'] = [
    'admin' => [
        'path'        => '/admin',
        'title'       => 'Admin Panel',
        'description' => 'Authenticated TONBANKCARD operations panel for provider, feature flag, content, and audit controls.',
        'og_type'     => 'website',
        'schema_type' => 'WebApplication',
        'sitemap'     => FALSE,
        'robots'      => 'noindex,nofollow',
    ],
    'admin-providers' => [
        'path'        => '/admin/providers',
        'title'       => 'Admin Providers',
        'description' => 'Authenticated provider and secret metadata controls.',
        'sitemap'     => FALSE,
        'robots'      => 'noindex,nofollow',
    ],
    'admin-feature-flags' => [
        'path'        => '/admin/feature-flags',
        'title'       => 'Admin Feature Flags',
        'description' => 'Authenticated feature flag controls.',
        'sitemap'     => FALSE,
        'robots'      => 'noindex,nofollow',
    ],
    'admin-audit-log' => [
        'path'        => '/admin/audit-log',
        'title'       => 'Admin Audit Log',
        'description' => 'Authenticated read-only audit log.',
        'sitemap'     => FALSE,
        'robots'      => 'noindex,nofollow',
    ],
];
